name: release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Release type"
        required: false
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          git_name: ${{ github.actor }}
          git_email: ${{ github.actor }}@users.noreply.github.com
          push: "false"
          prerelease: ${{ github.event.inputs.prerelease }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
      - name: Details
        run: |
          git show -s --format=%s
          echo "::set-output name=title::$(git show -s --format=%s)"
          echo "::set-output name=body::$(cat body.md)"
          rm body.md
          git diff HEAD
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release
          delete-branch: true
          title: Release ${{ steps.Details.outputs.title }}
          body: ${{ steps.Details.outputs.body }}
